import CryptoKit
import Darwin
import Foundation
import Testing
@testable import ForensicsCore

/// Independent format fixtures, not examples emitted by our decoder/carver.
/// JPEG/PNG were generated by Pillow 12.2; ZIP by Python's zipfile. PDF xrefs
/// and /Prev updates are built from literal object bytes below. Real PhotoRec
/// tests are explicit opt-in when the separately installed executable exists.
@Suite("Independent RAW carving corpus")
struct RecoveryCorpusTests {
    private static let photoRec = URL(fileURLWithPath: "/opt/homebrew/bin/photorec")

    @Test("JPEG, PNG, PDF and ZIP recover exact independent bytes and decode separately",
          .enabled(if: FileManager.default.isExecutableFile(atPath: photoRec.path)))
    func fourFormats() async throws {
        let payloads = try [CorpusPayload.jpeg(), CorpusPayload.png(), CorpusPayload.pdf("FORMAT PDF ORACLE"), CorpusPayload.zip()]
        let placed = payloads.enumerated().map { CorpusPlacement(payload: $0.element, offset: 65_536 + $0.offset * 1_048_576) }
        let fixture = try await CorpusFixture.make(placed)
        defer { fixture.remove() }
        let result = try await fixture.recover(using: Self.photoRec)
        #expect(result.artifacts.count == 4)
        for placement in placed {
            let artifact = try #require(result.artifacts.first { $0.sha256 == CorpusFixture.hash(placement.payload.bytes) })
            try fixture.verify(artifact, result: result, placement: placement)
            let analysis = try await fixture.decode(artifact, result: result)
            #expect(analysis.status == .decoded)
            #expect(analysis.mimeType == placement.payload.mime)
            if placement.payload.mime.hasPrefix("image/") {
                #expect(analysis.pixelWidth == 17 && analysis.pixelHeight == 13)
            } else if placement.payload.mime == "application/pdf" {
                #expect(analysis.pageCount == 1)
                #expect(DocumentContentSearch.search("FORMAT PDF ORACLE", in: analysis).hits.count == 1)
            } else {
                #expect(analysis.contentKind == .archive)
                #expect(DocumentContentSearch.search("ZIP INDEPENDENT ORACLE", in: analysis).hits.count == 1)
            }
        }
        try fixture.verifySourceAndReopen(result)
    }

    @Test("Two independent PDFs only 1,024 bytes apart remain separate exact candidates",
          .enabled(if: FileManager.default.isExecutableFile(atPath: photoRec.path)))
    func adjacentIndependentPDFs() async throws {
        let placed = [CorpusPlacement(payload: CorpusPayload.pdf("INDEPENDENT DOCUMENT A"), offset: 65_536),
                          CorpusPlacement(payload: CorpusPayload.pdf("INDEPENDENT DOCUMENT B"), offset: 66_560)]
        let fixture = try await CorpusFixture.make(placed)
        defer { fixture.remove() }
        let result = try await fixture.recover(using: Self.photoRec)
        #expect(result.artifacts.count == 2)
        for (index, placement) in placed.enumerated() {
            let artifact = try #require(result.artifacts.first { $0.sha256 == CorpusFixture.hash(placement.payload.bytes) })
            try fixture.verify(artifact, result: result, placement: placement)
            let analysis = try await fixture.decode(artifact, result: result)
            #expect(analysis.status == .decoded && analysis.pageCount == 1)
            #expect(DocumentContentSearch.search(index == 0 ? "DOCUMENT A" : "DOCUMENT B", in: analysis).hits.count == 1)
            #expect(DocumentContentSearch.search(index == 0 ? "DOCUMENT B" : "DOCUMENT A", in: analysis).hits.isEmpty)
        }
        try fixture.verifySourceAndReopen(result)
    }

    @Test("A valid PDF incremental update retains both EOF revisions as one exact candidate",
          .enabled(if: FileManager.default.isExecutableFile(atPath: photoRec.path)))
    func validIncrementalPDF() async throws {
        let placement = CorpusPlacement(payload: CorpusPayload.incrementalPDF(), offset: 65_536)
        let fixture = try await CorpusFixture.make([placement])
        defer { fixture.remove() }
        let result = try await fixture.recover(using: Self.photoRec)
        #expect(result.artifacts.count == 1)
        let artifact = try #require(result.artifacts.first)
        try fixture.verify(artifact, result: result, placement: placement)
        let analysis = try await fixture.decode(artifact, result: result)
        #expect(analysis.status == .decoded && analysis.pageCount == 1)
        #expect(DocumentContentSearch.search("INCREMENTAL UPDATED", in: analysis).hits.count == 1)
        #expect(DocumentContentSearch.search("INCREMENTAL ORIGINAL", in: analysis).hits.isEmpty)
        try fixture.verifySourceAndReopen(result)
    }

    @Test("Truncated, false-signature and fragmented inputs do not imply a complete recovery",
          .enabled(if: FileManager.default.isExecutableFile(atPath: photoRec.path)))
    func actualNegativeCorpus() async throws {
        let negatives = try CorpusPayload.negative()
        let placed = negatives.enumerated().map { CorpusPlacement(payload: $0.element, offset: 65_536 + $0.offset * 1_048_576) }
        let fixture = try await CorpusFixture.make(placed)
        defer { fixture.remove() }
        let result = try await fixture.recover(using: Self.photoRec)
        // This pinned corpus checks observed PhotoRec behaviour, not a promise
        // that malformed signatures can never produce future candidates.
        #expect(result.artifacts.isEmpty)
        #expect(result.status == .completed)
        #expect(result.warnings.contains { $0.contains("independent of file-format validity") })
        try fixture.verifySourceAndReopen(result)
    }

    @Test("Source-byte verification never certifies a malformed candidate or its deletion state",
          arguments: [0, 1, 2, 3])
    func verifiedMalformedCandidate(_ index: Int) async throws {
        let payload = try CorpusPayload.negative()[index]
        let placement = CorpusPlacement(payload: payload, offset: 65_536)
        let fixture = try await CorpusFixture.make([placement])
        defer { fixture.remove() }
        let tool = try fixture.reportedCandidateTool(payload)
        let result = try await fixture.recover(using: tool)
        let artifact = try #require(result.artifacts.first)
        #expect(result.artifacts.count == 1)
        try fixture.verify(artifact, result: result, placement: placement)
        let analysis = try await fixture.decode(artifact, result: result)
        #expect(artifact.validationStatus == .sourceBytesVerified)
        #expect(artifact.deletionStatus == "unknown")
        #expect(analysis.status == .failed)
        #expect(analysis.textPages.isEmpty && analysis.thumbnailPNG == nil)
        #expect(analysis.failureCode != nil)
        let report = RecoveryReportBuilder.renderMarkdown(result: result, analyses: [artifact.id: analysis])
        #expect(report.contains("sourceBytesVerified"))
        #expect(report.contains("Decoder observation: failed"))
        #expect(report.contains("Deletion status: unknown"))
        try fixture.verifySourceAndReopen(result)
    }
}

private struct CorpusPayload {
    let bytes: Data
    let suffix: String
    let mime: String

    static func jpeg() throws -> Self {
        let encoded = "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAANABEDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDzKiiivUPJCiiigD//2Q=="
        let bytes = try #require(Data(base64Encoded: encoded))
        try #require(bytes.count == 637)
        try #require(CorpusFixture.hash(bytes) == "2e5b2f3edfd312117d4afb4289c3dc4fccee92bf142f0c3d2d4327badc108a95")
        return Self(bytes: bytes, suffix: "jpg", mime: "image/jpeg")
    }
    static func png() throws -> Self {
        Self(bytes: try #require(Data(base64Encoded: "iVBORw0KGgoAAAANSUhEUgAAABEAAAANCAIAAADAGxJNAAAAHklEQVR4nGMUtI1lIBEwkaphVA8YMDGQDphG9TAAAObxAMVXg9PrAAAAAElFTkSuQmCC")), suffix: "png", mime: "image/png")
    }
    static func zip() throws -> Self {
        Self(bytes: try #require(Data(base64Encoded: "UEsDBBQAAAAIAPcGSF05ryzVFwAAABcAAAAKAAAAb3JhY2xlLnR4dIvyDFDw9HNxDXAFEn4hCv5Bjs4+rlwAUEsBAhQDFAAAAAgA9wZIXTmvLNUXAAAAFwAAAAoAAAAAAAAAAAAAAIABAAAAAG9yYWNsZS50eHRQSwUGAAAAAAEAAQA4AAAAPwAAAAAA")), suffix: "zip", mime: "application/zip")
    }
    static func pdf(_ text: String) -> Self {
        Self(bytes: pdfBytes(text).data, suffix: "pdf", mime: "application/pdf")
    }
    static func incrementalPDF() -> Self {
        let original = pdfBytes("INCREMENTAL ORIGINAL")
        let stream = "BT /F1 18 Tf 40 100 Td (INCREMENTAL UPDATED) Tj ET\n"
        let objectOffset = original.data.count
        var data = original.data
        data.append(Data("5 0 obj\n<< /Length \(stream.utf8.count) >>\nstream\n\(stream)endstream\nendobj\n".utf8))
        let xref = data.count
        data.append(Data("xref\n5 1\n\(String(format: "%010d", objectOffset)) 00000 n \ntrailer\n<< /Size 6 /Root 1 0 R /Prev \(original.xref) >>\nstartxref\n\(xref)\n%%EOF\n".utf8))
        return Self(bytes: data, suffix: "pdf", mime: "application/pdf")
    }
    static func negative() throws -> [Self] {
        let png = try png().bytes
        let foreign = Data(String(repeating: "FOREIGN DATA", count: 46).utf8)
        return [Self(bytes: Data(png.prefix(44)), suffix: "png", mime: "image/png"),
                Self(bytes: Data(pdf("INDEPENDENT DOCUMENT A").bytes.prefix(200)), suffix: "pdf", mime: "application/pdf"),
                Self(bytes: Data([0xff,0xd8,0xff,0xe0,0x00,0x10]) + Data("JFIF\0NOT A JPEG".utf8) + Data([0xff,0xd9]), suffix: "jpg", mime: "image/jpeg"),
                Self(bytes: Data(png.prefix(40)) + foreign + Data(png.dropFirst(40)), suffix: "png", mime: "image/png")]
    }
    private static func pdfBytes(_ text: String) -> (data: Data, xref: Int) {
        let stream = "BT /F1 18 Tf 40 100 Td (\(text)) Tj ET\n"
        let objects = ["<< /Type /Catalog /Pages 2 0 R >>", "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
                       "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 200] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
                       "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>", "<< /Length \(stream.utf8.count) >>\nstream\n\(stream)endstream"]
        var data = Data("%PDF-1.4\n".utf8), offsets: [Int] = []
        for (index, object) in objects.enumerated() {
            offsets.append(data.count)
            data.append(Data("\(index + 1) 0 obj\n\(object)\nendobj\n".utf8))
        }
        let xref = data.count
        data.append(Data("xref\n0 6\n0000000000 65535 f \n".utf8))
        for offset in offsets { data.append(Data("\(String(format: "%010d", offset)) 00000 n \n".utf8)) }
        data.append(Data("trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n\(xref)\n%%EOF\n".utf8))
        return (data, xref)
    }
}

private struct CorpusPlacement {
    let payload: CorpusPayload
    let offset: Int
}

private struct CorpusFixture {
    let root: URL
    let source: URL
    let bytes: Data
    let forensicCase: ForensicCase
    var evidence: EvidenceRecord { forensicCase.manifest.evidence[0] }
    static func make(_ placements: [CorpusPlacement]) async throws -> Self {
        let root = FileManager.default.temporaryDirectory.resolvingSymlinksInPath().appendingPathComponent("recovery-corpus-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: false)
        do {
            var bytes = Data(repeating: 0, count: 8 * 1_048_576)
            for placement in placements {
                bytes.replaceSubrange(placement.offset..<placement.offset + placement.payload.bytes.count, with: placement.payload.bytes)
            }
            let source = root.appendingPathComponent("synthetic.dd")
            try bytes.write(to: source, options: .withoutOverwriting)
            let created = try CaseStore.create(name: "Independent recovery corpus", in: root)
            let inspection = try await ImageInspector.inspect(url: source) { _ in }
            let forensicCase = try CaseStore.adding(image: inspection, to: created)
            return Self(root: root, source: source, bytes: bytes, forensicCase: forensicCase)
        } catch { try? FileManager.default.removeItem(at: root); throw error }
    }
    func recover(using tool: URL) async throws -> CarvingResult {
        try await PhotoRecRecoveryService(executableURL: tool).recover(evidence: evidence, in: forensicCase,
            options: RecoveryOptions(timeout: 60))
    }
    func verify(_ artifact: CarvedArtifact, result: CarvingResult, placement: CorpusPlacement) throws {
        #expect(artifact.sha256 == Self.hash(placement.payload.bytes))
        #expect(artifact.byteCount == Int64(placement.payload.bytes.count))
        #expect(artifact.validationStatus == .sourceBytesVerified && artifact.deletionStatus == "unknown")
        #expect(artifact.verifiedByteRuns == [RecoveryByteRun(outputOffset: 0, sourceOffset: Int64(placement.offset), length: artifact.byteCount)])
        #expect(try RecoveryResultStore.readArtifact(artifact: artifact, result: result, in: forensicCase.bundleURL,
            maximumBytes: artifact.byteCount) == placement.payload.bytes)
        let destination = root.appendingPathComponent("export-\(artifact.id.uuidString)")
        let receipt = try RecoveryResultStore.export(artifact: artifact, result: result, in: forensicCase.bundleURL, to: destination)
        #expect(receipt.sha256 == Self.hash(placement.payload.bytes))
        #expect(try Data(contentsOf: destination) == placement.payload.bytes)
    }
    func decode(_ artifact: CarvedArtifact, result: CarvingResult) async throws -> DocumentAnalysis {
        let url = try RecoveryResultStore.artifactURL(artifact: artifact, result: result, in: forensicCase.bundleURL)
        return try await DocumentAnalysisClient(helperURL: recoveryCorpusDecoder()).analyze(DocumentInput(fileURL: url,
            expectedSHA256: artifact.sha256, expectedByteCount: artifact.byteCount))
    }
    func verifySourceAndReopen(_ result: CarvingResult) throws {
        #expect(try Data(contentsOf: source) == bytes)
        #expect(Self.hash(bytes) == evidence.sha256)
        let reopened = try CaseStore.open(at: forensicCase.bundleURL)
        #expect(reopened.manifest == forensicCase.manifest)
        #expect(try RecoveryResultStore.latest(evidenceID: evidence.id, in: reopened.bundleURL) == result)
    }
    func reportedCandidateTool(_ payload: CorpusPayload) throws -> URL {
        let tool = root.appendingPathComponent("synthetic-reporter.sh")
        let xml = "<dfxml><source><image_size>\(bytes.count)</image_size></source><fileobject><filename>candidate.\(payload.suffix)</filename><filesize>\(payload.bytes.count)</filesize><byte_runs><byte_run offset='0' img_offset='65536' len='1024'/></byte_runs></fileobject></dfxml>"
        let script = """
        #!/bin/sh
        if [ "$1" = /version ]; then printf 'PhotoRec synthetic report-boundary fixture\n'; exit 0; fi
        /bin/mkdir recovered.1 || exit 1
        /bin/dd if=input.raw of=recovered.1/candidate.\(payload.suffix) bs=1 skip=65536 count=\(payload.bytes.count) 2>/dev/null || exit 1
        printf '%s' \(Self.quote(xml)) > recovered.1/report.xml
        """
        try Data(script.utf8).write(to: tool, options: .withoutOverwriting)
        guard Darwin.chmod(tool.path, 0o700) == 0 else { throw RecoveryError.unavailable }
        return tool
    }
    static func hash(_ data: Data) -> String { SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined() }
    private static func quote(_ value: String) -> String { "'" + value.replacingOccurrences(of: "'", with: "'\"'\"'") + "'" }
    func remove() { try? FileManager.default.removeItem(at: root) }
}

func recoveryCorpusDecoder() throws -> URL {
    let adjacent = Bundle(for: RecoveryCorpusTestAnchor.self).bundleURL.deletingLastPathComponent().appendingPathComponent("NFDocumentDecoder")
    if Darwin.access(adjacent.path, X_OK) == 0 { return adjacent }
    var directory = URL(fileURLWithPath: CommandLine.arguments[0]).deletingLastPathComponent()
    for _ in 0..<5 {
        let candidate = directory.appendingPathComponent("NFDocumentDecoder")
        if Darwin.access(candidate.path, X_OK) == 0 { return candidate }
        directory.deleteLastPathComponent()
    }
    throw DocumentAnalysisError.unavailable
}

private final class RecoveryCorpusTestAnchor: NSObject {}
